language: python
sudo: false

env:
  - LUA="lua 5.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

# Add tests and coverage here?
